name: Unit Ontology Comparison
on: [push, pull_request, workflow_dispatch]

jobs:
  compare:
    runs-on: ubuntu-latest
    container: ghcr.io/fusion-jena/abecto:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Run ABECTO Unit Ontology Comparison
        run: abecto --reportOn "http://www.ontology-of-units-of-measure.org/resource/om-2/" --export deviations=unit-ontology-comparison-deviations-om2.csv --failOnDeviation .github/workflows/unit-ontology-comparison.trig
      - name: Archive OM deviations report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: OM deviations report
          path: unit-ontology-comparison-deviations-om2.csv
